from z3 import *
xp_1 = Int('xp_1')
hp_1 = Int('hp_1')
hp_0 = Int('hp_0')
xp_0 = Int('xp_0')
endp_0 = Int('endp_0')
zp_0 = Int('zp_0')
yp_0 = Int('yp_0')
yp_1 = Int('yp_1')
zp_1 = Int('zp_1')
endp_1 = Int('endp_1')

z0_eq_z1=Bool('z0_eq_z1')
y0_eq_y1=Bool('y0_eq_y1')
x0_eq_x1=Bool('x0_eq_x1')
x0_gt_0=Bool('x0_gt_0')
p_synth_1=Bool('p_synth_1')
p_synth_2=Bool('p_synth_2')
p_synth_3=Bool('p_synth_3')
p_synth_9=Bool('p_synth_9')
p_synth_4=Bool('p_synth_4')
y_gteq_0_0=Bool('y_gteq_0_0')
z_gteq_0_0=Bool('z_gteq_0_0')
abs_end_0=Bool('abs_end_0')
abs_h_0=Bool('abs_h_0')
y_gteq_0_1=Bool('y_gteq_0_1')
z_gteq_0_1=Bool('z_gteq_0_1')
abs_end_1=Bool('abs_end_1')
abs_h_1=Bool('abs_h_1')

z0_eq_z1p = ((zp_0 == zp_1))
y0_eq_y1p = ((yp_0 == yp_1))
x0_eq_x1p = ((xp_0 == xp_1))
x0_gt_0p = ((xp_0 > 0))
p_synth_1p = ((xp_1 < zp_1))
p_synth_2p = ((xp_1 == zp_0))
p_synth_3p = ((xp_1 == hp_1))
p_synth_9p = ((hp_1 == zp_1))
p_synth_4p = ((xp_1 == zp_1 - xp_1))
y_gteq_0_0p = ((yp_0 >= 0))
z_gteq_0_0p = ((zp_0 >= 0))
abs_end_0p = ((1 == endp_0))
abs_h_0p = ((1 == hp_0))
y_gteq_0_1p = ((yp_1 >= 0))
z_gteq_0_1p = ((zp_1 >= 0))
abs_end_1p = ((1 == endp_1))
abs_h_1p = ((1 == hp_1))

a=simplify(And(And(And(z0_eq_z1p == True,        y0_eq_y1p == False,        x0_eq_x1p == True,        x0_gt_0p == True,        p_synth_1p == False,        p_synth_2p == False,        p_synth_3p == True,        p_synth_9p == False,        p_synth_4p == False,        y_gteq_0_0p == True,        z_gteq_0_0p == True,        abs_end_0p == True,        abs_h_0p == False,        y_gteq_0_1p == True,        z_gteq_0_1p == True,        abs_end_1p == True,        abs_h_1p == True))))
print(a.sexpr())
