from z3 import *
hp_1 = Int('hp_1')
lp_0 = Int('lp_0')
countp_0 = Int('countp_0')
hp_0 = Int('hp_0')
countp_1 = Int('countp_1')
lp_1 = Int('lp_1')

l0_eq_l1=Bool('l0_eq_l1')
count0_eq_2=Bool('count0_eq_2')
count1_eq_2=Bool('count1_eq_2')
p_synth_1=Bool('p_synth_1')
count_eq_0_0=Bool('count_eq_0_0')
h_gt_0_0=Bool('h_gt_0_0')
count_eq_0_1=Bool('count_eq_0_1')
h_gt_0_1=Bool('h_gt_0_1')

l0_eq_l1p = ((lp_0 == lp_1))
count0_eq_2p = ((countp_0 == 2))
count1_eq_2p = ((countp_1 == 2))
p_synth_1p = ((hp_1 == lp_1 - lp_0))
count_eq_0_0p = ((countp_0 == 0))
h_gt_0_0p = ((hp_0 > 0))
count_eq_0_1p = ((countp_1 == 0))
h_gt_0_1p = ((hp_1 > 0))

a=simplify(And(And(And(l0_eq_l1p == False,        count0_eq_2p == True,        count1_eq_2p == True,        p_synth_1p == False,        count_eq_0_0p == False,        h_gt_0_0p == True,        count_eq_0_1p == False,        h_gt_0_1p == True))))
print(a.sexpr())
