from z3 import *
np_0 = Int('np_0')
sump_0 = Int('sump_0')
sump_1 = Int('sump_1')
ip_1 = Int('ip_1')
ip_0 = Int('ip_0')
np_1 = Int('np_1')

i0_eq_0=Bool('i0_eq_0')
i1_eq_0=Bool('i1_eq_0')
sum0_eq_sum1=Bool('sum0_eq_sum1')
n0_eq_n1=Bool('n0_eq_n1')
p_synth_1=Bool('p_synth_1')
p_synth_2=Bool('p_synth_2')
p_synth_3=Bool('p_synth_3')
p_synth_4=Bool('p_synth_4')
p_synth_5=Bool('p_synth_5')
p_synth_6=Bool('p_synth_6')
p_synth_7=Bool('p_synth_7')
p_synth_8=Bool('p_synth_8')
p_synth_9=Bool('p_synth_9')
p_synth_10=Bool('p_synth_10')
p_synth_11=Bool('p_synth_11')
p_synth_12=Bool('p_synth_12')
p_synth_13=Bool('p_synth_13')
p_synth_14=Bool('p_synth_14')
p_synth_15=Bool('p_synth_15')
p_synth_16=Bool('p_synth_16')
p_synth_17=Bool('p_synth_17')
p_synth_18=Bool('p_synth_18')
i_eq_n_0=Bool('i_eq_n_0')
i_lt_n_0=Bool('i_lt_n_0')
n_gt_0_0=Bool('n_gt_0_0')
i_eq_n_1=Bool('i_eq_n_1')
i_lt_n_1=Bool('i_lt_n_1')
n_gt_0_1=Bool('n_gt_0_1')

i0_eq_0p = ((0 == ip_0))
i1_eq_0p = ((0 == ip_1))
sum0_eq_sum1p = ((sump_0 == sump_1))
n0_eq_n1p = ((np_0 == np_1))
p_synth_1p = ((np_0 == 1))
p_synth_2p = ((sump_0 == sump_1 - ip_0))
p_synth_3p = ((sump_0 == sump_1 - 1))
p_synth_4p = ((np_0 == 2))
p_synth_5p = ((np_0 == 3*ip_1))
p_synth_6p = ((np_0 == 3))
p_synth_7p = ((np_0 == 4*ip_1))
p_synth_8p = ((np_0 == 4))
p_synth_9p = ((np_0 == 5*ip_1))
p_synth_10p = ((np_0 == 5))
p_synth_11p = ((np_0 == 6*ip_1))
p_synth_12p = ((np_0 == 6))
p_synth_13p = ((np_0 == 7*ip_1))
p_synth_14p = ((np_0 == 7))
p_synth_15p = ((np_0 == 8*ip_1))
p_synth_16p = ((np_0 == 8))
p_synth_17p = ((ip_1 == 1))
p_synth_18p = ((np_0 == 2*ip_1))
i_eq_n_0p = ((ip_0 == np_0))
i_lt_n_0p = ((ip_0 < np_0))
n_gt_0_0p = ((np_0 > 0))
i_eq_n_1p = ((ip_1 == np_1))
i_lt_n_1p = ((ip_1 < np_1))
n_gt_0_1p = ((np_1 > 0))

a=simplify(And(And(And(i0_eq_0p == True,        i1_eq_0p == False,        sum0_eq_sum1p == False,        n0_eq_n1p == True,        p_synth_1p == False,        p_synth_2p == False,        p_synth_3p == False,        p_synth_4p == False,        p_synth_5p == False,        p_synth_6p == False,        p_synth_7p == False,        p_synth_8p == False,        p_synth_9p == False,        p_synth_10p == False,        p_synth_11p == False,        p_synth_12p == False,        p_synth_13p == False,        p_synth_14p == False,        p_synth_15p == False,        p_synth_16p == False,        p_synth_17p == False,        p_synth_18p == False,        i_eq_n_0p == False,        i_lt_n_0p == True,        n_gt_0_0p == True,        i_eq_n_1p == True,        i_lt_n_1p == False,        n_gt_0_1p == True))))
print(a.sexpr())
