from z3 import *
pcp_0 = Int('pcp_0')
hp_1 = Int('hp_1')
pcp_1 = Int('pcp_1')
hp_0 = Int('hp_0')
ip_0 = Int('ip_0')
maxp_0 = Int('maxp_0')
yp_0 = Int('yp_0')
ip_1 = Int('ip_1')
yp_1 = Int('yp_1')
vp_0 = Int('vp_0')
vp_1 = Int('vp_1')
maxp_1 = Int('maxp_1')

y0_eq_y1=Bool('y0_eq_y1')
i0_eq_i1=Bool('i0_eq_i1')
max0_eq_max1=Bool('max0_eq_max1')
p_synth_1=Bool('p_synth_1')
p_synth_2=Bool('p_synth_2')
p_synth_3=Bool('p_synth_3')
p_synth_4=Bool('p_synth_4')
pc_eq_0_0=Bool('pc_eq_0_0')
pc_eq_1_0=Bool('pc_eq_1_0')
i_eq_max_0=Bool('i_eq_max_0')
pc_eq_0_1=Bool('pc_eq_0_1')
pc_eq_1_1=Bool('pc_eq_1_1')
i_eq_max_1=Bool('i_eq_max_1')

y0_eq_y1p = ((yp_0 == yp_1))
i0_eq_i1p = ((ip_0 == ip_1))
max0_eq_max1p = ((maxp_0 == maxp_1))
p_synth_1p = ((ip_0 < hp_1))
p_synth_2p = ((yp_0 == vp_1))
p_synth_3p = ((hp_1 == ip_0 + 1))
p_synth_4p = ((hp_1 == hp_0))
pc_eq_0_0p = ((pcp_0 == 0))
pc_eq_1_0p = ((pcp_0 == 1))
i_eq_max_0p = ((ip_0 == maxp_0))
pc_eq_0_1p = ((pcp_1 == 0))
pc_eq_1_1p = ((pcp_1 == 1))
i_eq_max_1p = ((ip_1 == maxp_1))

a=simplify(And(And(And(y0_eq_y1p == False,        i0_eq_i1p == False,        max0_eq_max1p == True,        p_synth_1p == True,        p_synth_2p == False,        p_synth_3p == True,        p_synth_4p == False,        pc_eq_0_0p == True,        pc_eq_1_0p == False,        i_eq_max_0p == False,        pc_eq_0_1p == False,        pc_eq_1_1p == False,        i_eq_max_1p == True))))
print(a.sexpr())
