from z3 import *
xp_1 = Int('xp_1')
hp_1 = Int('hp_1')
countp_0 = Int('countp_0')
hp_0 = Int('hp_0')
xp_0 = Int('xp_0')
countp_1 = Int('countp_1')

x0_eq_x1=Bool('x0_eq_x1')
abs_h_0=Bool('abs_h_0')
count_0_0=Bool('count_0_0')
count_1_0=Bool('count_1_0')
abs_h_1=Bool('abs_h_1')
count_0_1=Bool('count_0_1')
count_1_1=Bool('count_1_1')

x0_eq_x1p = ((xp_0 == xp_1))
abs_h_0p = ((1 == hp_0))
count_0_0p = ((countp_0 == 0))
count_1_0p = ((countp_0 == 1))
abs_h_1p = ((1 == hp_1))
count_0_1p = ((countp_1 == 0))
count_1_1p = ((countp_1 == 1))

a=simplify(And(And(And(x0_eq_x1p == False,        abs_h_0p == True,        count_0_0p == False,        count_1_0p == True,        abs_h_1p == False,        count_0_1p == False,        count_1_1p == True))))
print(a.sexpr())
