from z3 import *
x_1 = Int('x_1')
h_1 = Int('h_1')
count_0 = Int('count_0')
h_0 = Int('h_0')
x_0 = Int('x_0')
count_1 = Int('count_1')

x0_eq_x1=Bool('x0_eq_x1')
p_synth_1=Bool('p_synth_1')
p_synth_2=Bool('p_synth_2')
p_synth_3=Bool('p_synth_3')
p_synth_4=Bool('p_synth_4')
p_synth_5=Bool('p_synth_5')
abs_h_0=Bool('abs_h_0')
count_0_0=Bool('count_0_0')
abs_h_1=Bool('abs_h_1')
count_0_1=Bool('count_0_1')

x0_eq_x1 = ((x_0 == x_1))
p_synth_1 = ((x_1 == 8))
p_synth_2 = ((x_1 < 42))
p_synth_3 = ((x_1 == 42))
p_synth_4 = ((x_1 == x_1))
p_synth_5 = ((x_1 == x_1))
abs_h_0 = ((1 == h_0))
count_0_0 = ((count_0 == 0))
abs_h_1 = ((1 == h_1))
count_0_1 = ((count_1 == 0))

a=simplify(And(And(x0_eq_x1 == False,    p_synth_1 == False,    p_synth_2 == False,    p_synth_3 == False,    p_synth_4 == True,    p_synth_5 == True,    abs_h_0 == True,    count_0_0 == False,    abs_h_1 == True,    count_0_1 == False)))
print(a.sexpr())
